name: Deploy

on: 
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v1

      - name: Deploying latest commit
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DO_SSH_HOST }}
          username: ${{ secrets.DO_SSH_USER }}
          password: ${{ secrets.DO_SSH_PASS }}
          port: ${{ secrets.DO_SSH_PORT }}
          script: pm2 deploy wabotEcosystem.config.js production update
